const data = {
  name: "Academic & Research",
  hidden: 0,
  type: "",
  checkbox: 1,
  weight: 11,
  private: 0,
  restricted: 0,
  lat: 0,
  lng: 0,
  level: 0,
  schedule: "",
  icon: "/assets/336/academics-marker_5.png",
  dynamic_label: 0,
  dynamic_label_v2: 0,
  floor_level: 0,
  abbr_zoom_level: null,
  popup: "",
  description: "",
  keywords: "",
  panorama: 0,
  labels: "",
  locationDisplay: "sidebar",
  onByDefault: 0,
  popupUrl: "",
  catId: 2732,
  mapId: 336,
  parent: 21218,
  maxZoom: null,
  minZoom: null,
  markerAlt: 130,
  mapAlt: 0,
  tileExtension: "png",
  tileType: "",
  tileParams: "",
  tileUrl: "",
  singleSelect: 0,
  listIcon: "/assets/336/academics-list_5.png",
  children: {
    locations: [
      {
        catId: 2732,
        altitude: 0,
        lat: 40.011089,
        lng: -105.273895,
        mapId: 336,
        id: 193794,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136157,
        name: "Armory (ARMR)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.008129,
        lng: -105.246323,
        mapId: 336,
        id: 193819,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136182,
        name: "Astrophysical Research Lab (ARL)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.010651,
        lng: -105.270088,
        mapId: 336,
        id: 193824,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136187,
        name: "Clare Small Arts & Sciences (CLRE)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.010868,
        lng: -105.274429,
        mapId: 336,
        id: 193828,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136191,
        name: "Continuing Education (CEDU)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007984,
        lng: -105.271416,
        mapId: 336,
        id: 193829,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136192,
        name: "Cooperative Institute for Research in Environmental Sciences (CIRES)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007343,
        lng: -105.271111,
        mapId: 336,
        id: 193831,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136194,
        name: "Cristol Chemistry & Biochemistry (CHEM)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.00703,
        lng: -105.273392,
        mapId: 336,
        id: 193838,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136201,
        name: "Denison Arts & Sciences (DEN)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007652,
        lng: -105.26181,
        mapId: 336,
        id: 193839,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136202,
        name: "Gallogly Discovery Learning Center (DLC)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.00806,
        lng: -105.268257,
        mapId: 336,
        id: 193840,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136203,
        name: "Duane D-Wing (DDW)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.008068,
        lng: -105.267349,
        mapId: 336,
        id: 193841,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136204,
        name: "Duane Physics (DUAN)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007935,
        lng: -105.274513,
        mapId: 336,
        id: 193844,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136207,
        name: "Economics (ECON)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007484,
        lng: -105.273575,
        mapId: 336,
        id: 193852,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136215,
        name: "Lucile Berkeley Buchanan (LBB)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.008244,
        lng: -105.271767,
        mapId: 336,
        id: 193853,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136216,
        name: "Ekeley Sciences (EKLC)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007172,
        lng: -105.262894,
        mapId: 336,
        id: 193854,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136217,
        name: "Engineering Center (EC)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.006699,
        lng: -105.2631,
        mapId: 336,
        id: 193855,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: 0
        },
        mrkId: 136218,
        name: "Environmental Sustainability Wing (ECES)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007107,
        lng: -105.262604,
        mapId: 336,
        id: 193856,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          rate: 0
        },
        mrkId: 136219,
        name: "Civil Engineering Wing (ECCE)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007988,
        lng: -105.263092,
        mapId: 336,
        id: 193857,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136220,
        name: "Engineering Center North Wing (ECNW)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007626,
        lng: -105.262558,
        mapId: 336,
        id: 193858,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          rate: 0
        },
        mrkId: 136221,
        name: "Electrical Engineering Wing (ECEE)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007729,
        lng: -105.263542,
        mapId: 336,
        id: 193859,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          rate: 0
        },
        mrkId: 136222,
        name: "Mechanical Engineering Wing (ECME)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.006729,
        lng: -105.263687,
        mapId: 336,
        id: 193860,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136223,
        name: "Computer Science Wing (ECCS)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007126,
        lng: -105.269218,
        mapId: 336,
        id: 193861,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136224,
        name: "CMDI Department of Environmental Design (ENVD)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.002113,
        lng: -105.263336,
        mapId: 336,
        id: 193871,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136233,
        name: "Miramontes Baca Education (MBE)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.008461,
        lng: -105.267853,
        mapId: 336,
        id: 193874,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136236,
        name: "Gamow Tower (W-GT)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.008247,
        lng: -105.274834,
        mapId: 336,
        id: 193875,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136237,
        name: "Gates Woodruff Women's Studies Cottage (COTT)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.008823,
        lng: -105.268196,
        mapId: 336,
        id: 193876,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136238,
        name: "Gold Biosciences Building (GOLD)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.00832,
        lng: -105.274239,
        mapId: 336,
        id: 193877,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136239,
        name: "Guggenheim Geography (GUGG)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.009315,
        lng: -105.274963,
        mapId: 336,
        id: 193879,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: 0
        },
        mrkId: 136241,
        name: "Hale Science (HALE)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007641,
        lng: -105.272766,
        mapId: 336,
        id: 193881,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136243,
        name: "Hellems Arts & Sciences (HLMS)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.009296,
        lng: -105.271881,
        mapId: 336,
        id: 193885,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136247,
        name: "Eaton Humanities (HUMN)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.006191,
        lng: -105.268982,
        mapId: 336,
        id: 193889,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136251,
        name: "Imig Music (MUS)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.011856,
        lng: -105.253014,
        mapId: 336,
        id: 193896,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136257,
        name: "Institute for Behavioral Genetics (IBG)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.011398,
        lng: -105.274429,
        mapId: 336,
        id: 193898,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136259,
        name: "Richard Jessor Building (JESS)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.006981,
        lng: -105.261795,
        mapId: 336,
        id: 193908,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136269,
        name: "Drescher Undergraduate Engineering Integrated Teaching & Learning Laboratory (ITLL)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.006111,
        lng: -105.275871,
        mapId: 336,
        id: 193909,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136270,
        name: "International English Center (IEC)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007416,
        lng: -105.268654,
        mapId: 336,
        id: 193910,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136271,
        name: "JILA (JILA)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.008633,
        lng: -105.249092,
        mapId: 336,
        id: 193911,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136272,
        name: "Jennie Smoly Caruthers Biotech Building (BIOT)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.00816,
        lng: -105.270226,
        mapId: 336,
        id: 193913,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136274,
        name: "Ketchum Arts & Sciences (KTCH)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.005684,
        lng: -105.263451,
        mapId: 336,
        id: 193917,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: 0
        },
        mrkId: 136278,
        name: "Koelbel Building: Leeds School of Business (KOBL)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.00927,
        lng: -105.247551,
        mapId: 336,
        id: 193919,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136280,
        name: "LASP Space Technology Research Center (LSTR)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.008583,
        lng: -105.261688,
        mapId: 336,
        id: 193920,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136281,
        name: "Lesser House (LESS)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.009895,
        lng: -105.242149,
        mapId: 336,
        id: 193923,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136283,
        name: "Sustainability, Energy & Environment Community (SEEC)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.010052,
        lng: -105.272743,
        mapId: 336,
        id: 193924,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136284,
        name: "Macky Auditorium (MCKY)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007755,
        lng: -105.264542,
        mapId: 336,
        id: 193928,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136287,
        name: "Mathematics Building (MATH)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.009708,
        lng: -105.273621,
        mapId: 336,
        id: 193936,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136290,
        name: "McKenna Languages (MKNA)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.008606,
        lng: -105.269226,
        mapId: 336,
        id: 193937,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136291,
        name: "Muenzinger Psychology (MUEN)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.008839,
        lng: -105.270905,
        mapId: 336,
        id: 193942,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136296,
        name: "Norlin Library (LIBR)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.009403,
        lng: -105.273338,
        mapId: 336,
        id: 193948,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136300,
        name: "Old Main (MAIN)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.009155,
        lng: -105.269073,
        mapId: 336,
        id: 193952,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136303,
        name: "Porter Biosciences (PORT)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.008892,
        lng: -105.269661,
        mapId: 336,
        id: 193957,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136307,
        name: "Ramaley Biology (RAMY)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.010708,
        lng: -105.252464,
        mapId: 336,
        id: 193966,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136316,
        name: "Research Park Greenhouse (GH-3)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007648,
        lng: -105.269966,
        mapId: 336,
        id: 193967,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136317,
        name: "Roser ATLAS Center (ATLS)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.012856,
        lng: -105.249786,
        mapId: 336,
        id: 193969,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: 0
        },
        mrkId: 136318,
        name: "New Physics Laboratory (NPL)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.003796,
        lng: -105.262985,
        mapId: 336,
        id: 193973,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136322,
        name: "Sommers-Bausch Observatory (OBSV)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.011971,
        lng: -105.245804,
        mapId: 336,
        id: 193975,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136323,
        name: "Space Science Building (SPSC)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.003979,
        lng: -105.262505,
        mapId: 336,
        id: 193976,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136324,
        name: "Speech, Language & Hearing Sciences (SLHS)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007538,
        lng: -105.270477,
        mapId: 336,
        id: 193996,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136341,
        name: "Visual Arts Complex (VAC)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.001278,
        lng: -105.262169,
        mapId: 336,
        id: 194001,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136345,
        name: "Wolf Law (WLAW)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.008839,
        lng: -105.24131,
        mapId: 336,
        id: 204809,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 144218,
        name: "Sustainability, Energy & Environment Laboratory (SEEL)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.017944,
        lng: -105.246826,
        mapId: 336,
        id: 204895,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 144280,
        name: "Center for Innovation & Creativity (CINC)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.00806,
        lng: -105.265862,
        mapId: 336,
        id: 222147,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: 0
        },
        mrkId: 136169,
        name: "Benson Earth Sciences (BESC)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.011772,
        lng: -105.275581,
        mapId: 336,
        id: 224591,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 161692,
        name: "Temporary Building 82 (TB82)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.010944,
        lng: -105.273537,
        mapId: 336,
        id: 224596,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: 0
        },
        mrkId: 161697,
        name: "Arts & Sciences Office Building 1 (OB1)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.026852,
        lng: -105.24604,
        mapId: 336,
        id: 224605,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 161704,
        name: "Wilderness Place (WILD)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.012783,
        lng: -105.253258,
        mapId: 336,
        id: 224638,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 161729,
        name: "National Snow & Ice Data Center",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.011406,
        lng: -105.275276,
        mapId: 336,
        id: 268233,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: 0
        },
        mrkId: 192371,
        name: "Center for Native American & Indigenous Studies (GVAS)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.010094,
        lng: -105.243935,
        mapId: 336,
        id: 429230,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 186315,
        name: "Aerospace Engineering Sciences (AERO)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007118,
        lng: -105.263634,
        mapId: 336,
        id: 432490,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 314556,
        name: "Engineering Classroom Wing (ECCR)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007362,
        lng: -105.263367,
        mapId: 336,
        id: 432491,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 314557,
        name: "Engineering Office Tower (ECOT)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007351,
        lng: -105.262634,
        mapId: 336,
        id: 432492,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 314558,
        name: "Engineering Administration Wing (ECAD)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.007782,
        lng: -105.263062,
        mapId: 336,
        id: 432495,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 314560,
        name: "Engineering North Tower (ECNT)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.006863,
        lng: -105.262604,
        mapId: 336,
        id: 432496,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 314561,
        name: "Engineering Stores & Labs (ECSL)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.006916,
        lng: -105.263115,
        mapId: 336,
        id: 432497,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 314562,
        name: "Engineering South Tower (ECST)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.03223,
        lng: -105.535942,
        mapId: 336,
        id: 471538,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 345216,
        name: "Mountain Research Station",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.006496,
        lng: -105.263451,
        mapId: 336,
        id: 568293,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 415832,
        name: "Rustandy Building",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.010387,
        lng: -105.241302,
        mapId: 336,
        id: 1114589,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 839063,
        name: "Wind Tunnel Building (WIND)",
        reference: "",
        schedule: "",
        shape: {
          type: "polygon",
          color: "#ff0000",
          opacity: 0.8,
          weight: 4,
          colorNormal: "#ff0000",
          opacityNormal: 0.8,
          weightNormal: 4,
          colorHover: "#ff0000",
          opacityHover: 0.8,
          weightHover: 4,
          strokeType: "solid",
          paths: [
            [40.0104336229141, -105.241471724625],
            [40.0103036662455, -105.241449150219],
            [40.0103410357854, -105.241136749571],
            [40.0103929069032, -105.241138934191],
            [40.0104712712544, -105.241165513733],
            [40.0104336229141, -105.241471724625]
          ],
          fillColor: "#ff0000",
          fillOpacity: 0.2,
          fillColorNormal: "#ff0000",
          fillOpacityNormal: 0.2,
          fillColorHover: "#ff0000",
          fillOpacityHover: 0.2,
          icon: false,
          position: false
        },
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      },
      {
        catId: 2732,
        altitude: 0,
        lat: 40.009621,
        lng: -105.268555,
        mapId: 336,
        id: 1116474,
        weight: 0,
        icon: "",
        level: [0],
        location_open: "",
        locationType: "standard",
        marker_feed: {
          feed: "",
          rate: null
        },
        mrkId: 136181,
        name: "Carlson Gymnasium (CARL)",
        reference: "",
        schedule: "",
        shape: "",
        minZoom: null,
        maxZoom: null,
        geojson_feature: null,
        iconSize: 35
      }
    ]
  }
};

export const buildings = data.children.locations;
